language: java
matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: osx
      osx_image: xcode13.1
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/qpid/*
