language: java
matrix:
  include:
    - os: linux
      jdk: openjdk11
      dist: xenial
    - os: osx
      osx_image: xcode12.5
script:
  - mvn test -Dtest='*Test, !ConnectionIntegrationTest#testConnectionFailsWhenUserSuppliesIllegalProperties'
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/qpid/*
