name: "Build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 16 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Build
        run: mvn -B clean verify

      - name: Archive Test Logs On Failure
        if: failure()
        run: tar -czvf surefire-reports-jdk-${{ matrix.java }}.tar.gz **/target/surefire-reports/*

      - name: Upload Test Logs On Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports-jdk-${{ matrix.java }}
          path: surefire-reports-jdk-${{ matrix.java }}.tar.gz
